Repository meilisearch/meilisearch-js-plugins, pull requests merged in 2021-03, with the labels that each got.

#322 Add objectID when primaryKey is provided
  README.md
  playgrounds/react/src/App.js
  src/index.ts
  src/types.ts
Labels: enhancement

#324 Update to v0.3.2
  package.json
Labels: skip-changelog

#344 Fix nested object being transfom into [object, object] in highlight
  src/format.ts
Labels: breaking-change, bug

#336 Fix react playground
  playgrounds/react/src/App.css
  playgrounds/react/src/App.js
Labels: skip-changelog

#352 update package to v0.4.0
  package.json
Labels: skip-changelog
