Repository meilisearch/meilisearch-js-plugins, pull requests merged in 2022-03, with the labels that each got.

#682 Add compatibility with hierarchicalMenu/breadcrumb/RatingsMenu in readme
  README.md
Labels: skip-changelog

#693 Update Bors badge
  README.md
Labels: skip-changelog

#695 Add possibility to show facets with 0 matching documents
  README.md
  src/adapter/search-request-adapter/__tests__/facets-distribution-assigns.tests.ts
  src/adapter/search-request-adapter/__tests__/filter-cache.tests.ts
  src/adapter/search-request-adapter/__tests__/search-params.tests.ts
  src/adapter/search-request-adapter/filters.ts
  src/adapter/search-request-adapter/search-resolver.ts
  src/adapter/search-response-adapter/pagination-adapter.ts
  src/adapter/search-response-adapter/search-response-adapter.ts
  src/cache/first-facets-distribution.ts
  src/cache/index.ts
  src/client/contexts.ts
  src/client/instant-meilisearch-client.ts
  src/types/types.ts
Labels: enhancement

#696 Fix hyperlinks of the table of contents
  README.md
Labels: skip-changelog

#701 Add link to explaination on how to set up refinementList
  README.md
Labels: skip-changelog

#703 Update version for the next release (v0.6.2)
  package.json
Labels: skip-changelog

#702 Add table of content for instant meilisearch customization
  README.md
Labels: skip-changelog

#707 Introduce finitePagination setting: remove default fetch of 200 documents
  README.md
  jest.config.js
  package.json
  src/adapter/search-request-adapter/__tests__/search-params.tests.ts
  src/adapter/search-request-adapter/search-params-adapter.ts
  src/adapter/search-request-adapter/search-resolver.ts
  src/adapter/search-response-adapter/pagination-adapter.ts
  src/adapter/search-response-adapter/search-response-adapter.ts
  src/client/instant-meilisearch-client.ts
  src/contexts/index.ts
  src/contexts/pagination-context.ts
  src/contexts/search-context.ts
  src/types/types.ts
  tests/pagination.tests.ts
Labels: enhancement, breaking-change

#720 Fix default value of hitsPerPage in readme
  README.md
  src/contexts/search-context.ts
Labels: skip-changelog
