Repository meilisearch/meilisearch-js-plugins, pull requests merged in 2022-07, with the labels that each got.

#791 Update version for the next release (v0.8.0)
  package.json
  src/package-version.ts
Labels: skip-changelog

#794 Update search key in playgrounds
  README.md
  playgrounds/angular/src/app/app.component.ts
  playgrounds/geo-javascript/src/app.js
  playgrounds/html/public/index.html
  playgrounds/javascript/src/app.js
  playgrounds/react/src/App.js
  playgrounds/vue/src/App.vue
Labels: skip-changelog

#801 Create new publish CI for beta versions
  .github/scripts/check-tag-format.sh
  .github/workflows/publish.yml
  CONTRIBUTING.md
Labels: skip-changelog

#752 fix links in Readme.md
  README.md
Labels: skip-changelog

#808 Add ability to clear cache to allow real-time refresh of search results.
  src/cache/search-cache.ts
  src/client/instant-meilisearch-client.ts
  src/types/types.ts
Labels: enhancement

#807 Fix links in readme
  README.md
Labels: skip-changelog

#806 Add beta testing in CI
  .github/scripts/beta-docker-version.sh
  .github/workflows/beta-tests.yml
Labels: skip-changelog

#809 Update version for the next release (v0.8.1)
  package.json
  src/package-version.ts
Labels: skip-changelog

#726 Object constructor for search parameters
  src/adapter/search-request-adapter/search-params-adapter.ts
Labels: skip-changelog, refactor

#810 Add correct docker image fetch in beta CI
  .github/workflows/beta-tests.yml
Labels: skip-changelog
