Repository meilisearch/meilisearch-js-plugins, pull requests merged in 2023-06, with the labels that each got.

#1122 Upgrade node version in CI workflows
  .github/workflows/meilisearch-prototype-tests.yml
  .github/workflows/pre-release-tests.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
Labels: maintenance

#1134 Update meilisearch js to v0.33.0
  packages/instant-meilisearch/__tests__/snippets.test.ts
  packages/instant-meilisearch/package.json
  yarn.lock
Labels: skip-changelog

#1125 Fix the documentation around prototype versions
  CONTRIBUTING.md
Labels: skip-changelog

#1140 Create first public version for autocomplete client
  playgrounds/autocomplete/package.json
Labels: skip-changelog

#1147 Make autocomplete public on npm
  packages/autocomplete-client/package.json
Labels: skip-changelog

#1149 Fix the publish CI not running on a prototype
  .github/workflows/publish.yml
Labels: skip-changelog

#1120 Change the repo's name and purpose
  CONTRIBUTING.md
  README.md
  package.json
  packages/autocomplete-client/README.md
  packages/autocomplete-client/package.json
  packages/instant-meilisearch/CHANGELOG.md
  packages/instant-meilisearch/README.md
  packages/instant-meilisearch/package.json
Labels: skip-changelog

#1161 Fix bug when sort-by contains geo points
  .changeset/dirty-mangos-tie.md
  packages/instant-meilisearch/__tests__/sort.test.ts
  packages/instant-meilisearch/src/contexts/search-context.ts
  packages/instant-meilisearch/src/contexts/sort-context.ts
Labels: bug

#1162 Add Meilisearch Cloud touchpoint in README.md section
  README.md
  packages/autocomplete-client/README.md
  packages/instant-meilisearch/README.md
Labels: skip-changelog
