Repository meilisearch/meilisearch-js-plugins, pull requests merged in 2023-03, with the labels that each got.

#1016 Fix initial facet distribution when using sortby
  .changeset/odd-spies-invite.md
  packages/instant-meilisearch/__tests__/first-facets-distribution.test.ts
  packages/instant-meilisearch/src/cache/first-facets-distribution.ts
  packages/instant-meilisearch/src/client/instant-meilisearch-client.ts
Labels: bug

#1039 Fix pre-release CI not triggering
  .github/workflows/pre-release-tests.yml
Labels: skip-changelog

#1038 Use multi search api for ms v1.1.0
  .changeset/fresh-countries-move.md
  README.md
  packages/instant-meilisearch/__tests__/search-resolver.test.ts
  packages/instant-meilisearch/package.json
  packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts
  packages/instant-meilisearch/src/adapter/search-request-adapter/search-resolver.ts
  packages/instant-meilisearch/src/adapter/search-response-adapter/hits-adapter.ts
  packages/instant-meilisearch/src/adapter/search-response-adapter/pagination-adapter.ts
  packages/instant-meilisearch/src/adapter/search-response-adapter/search-response-adapter.ts
  packages/instant-meilisearch/src/cache/__tests__/search-cache.test.ts
  packages/instant-meilisearch/src/cache/init-facets-distribution.ts
  packages/instant-meilisearch/src/cache/search-cache.ts
  packages/instant-meilisearch/src/client/config/index.ts
  packages/instant-meilisearch/src/client/instant-meilisearch-client.ts
  packages/instant-meilisearch/src/types/types.ts
  packages/instant-meilisearch/src/utils/array.ts
  packages/instant-meilisearch/src/utils/index.ts
  packages/instant-meilisearch/src/utils/validate.ts
  yarn.lock
Labels: enhancement

#1041 Add support for multiple sort attributes
  .changeset/red-fans-cross.md
  README.md
  packages/instant-meilisearch/__tests__/sort.test.ts
  packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts
  packages/instant-meilisearch/src/contexts/search-context.ts
  packages/instant-meilisearch/src/contexts/sort-context.ts
  packages/instant-meilisearch/src/types/types.ts
Labels: enhancement
