Repository meilisearch/meilisearch-js-plugins, pull requests merged in 2023-09, with the labels that each got.

#1251 Update dependabot.yml
  .github/dependabot.yml
Labels: skip-changelog

#1252 Fix `HierarchicalMenu` when `keepZeroFacets` is set to true
  .changeset/giant-clouds-smell.md
  packages/instant-meilisearch/src/cache/__tests__/fill-missing-facets.test.ts
  packages/instant-meilisearch/src/cache/init-facets-distribution.ts
  packages/instant-meilisearch/src/client/instant-meilisearch-client.ts
  playgrounds/local-react/src/components/MultiIndex.jsx
  playgrounds/local-react/src/components/SingleMovieIndex.jsx
  playgrounds/react/package.json
  yarn.lock
Labels: bug

#1257 Improve CONTRIBUTING.md about changeset
  CONTRIBUTING.md
Labels: documentation, skip-changelog
